### PR TITLE
Added command to turn on/off remote logging

### PR DESCRIPTION
**Pull request by bcorwin**
Use "e" to turn off remote logging (forces all logs to queue) and "d" to
turn it back on.

### CODE REVIEW

**Comment by cutreth** [comment]
Do you mind updating the views.commands with these new options too so it's all done at once?

**Comment by bcorwin** [comment]
Done and done.

**Comment by bcorwin** [comment]
I don't know what the close button is for. Are you supposed to do that once you merge them?

**Comment by cutreth** [comment]
Haha. Only close it if you don't want the pull request to happen. Otherwise it'll close automatically when I merge it.

Two corrections:
1) What the indentation for the line with 'd'.
2) Can we make the button labels more clear? Logging vs. data collection is confusing. One toggles data collection and API updates. The other toggles just API updates, right?

**Comment by cutreth** [comment]
Also, are there any issues if you use l/o/e/d in combination with each other? I assume hitting just one handle everything and there's no set one then set the other type stuff we have to do, right?

**Comment by cutreth** [comment]
OK. Looking at the code it seems like collection and logging are completely separate. o/l toggles data collection from the server and e/d toggles sends from the server to Django. Is that right? If so, I think we're good.

**Comment by bcorwin** [comment]
Yea, they're different (your interpretation is correct):
-- o/l turns everything off (no collecting data, no logging data)
-- e/d continues to collect data but it does not push it to django until you turn it back on. With this no data is lost

As for the indentation, we must have different tab settings in our editors. Which shouldn't be an issue in this case (since in that context spacing isn't important) but it could be an issue in the future.

**Comment by bcorwin** [comment]
I thought I did sync. What step did I miss?

**Comment by bcorwin** [comment]
Oh, I see now

**Pull request merged**
